name: prod-CD
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      working-directory: .


    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: say hello
        run: |
          echo hello
        shell: bash
