name: Create Release Tag

on:
  workflow_run:
    workflows: ["prod-CD"]  # CD 워크플로우 이름
    types:
      - completed

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $BRANCH_NAME"
          
          if [[ $BRANCH_NAME =~ (v[0-9]+\.[0-9]+\.[0-9]+) ]]; then
            TAG_VERSION="${BASH_REMATCH[1]}"
            echo "Version extracted: $TAG_VERSION"
            echo "::set-output name=tag::$TAG_VERSION"
          else
            echo "No version pattern found in branch name."
            exit 1
          fi

      - name: Create and push tag
        run: |
          TAG_VERSION=${{ steps.extract_version.outputs.tag }}
          echo "Creating and pushing tag: $TAG_VERSION"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag $TAG_VERSION
          git push origin $TAG_VERSION
